config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :front do
    root 'static_pages#home'

    get 'contact', to: 'static_pages#contact'
    get 'ded-moroz-i-snegurochka', to: 'static_pages#new_year', as: 'new_year'
    resources :requests
    resources :services
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/front/requests_controller.rb
class Front::RequestsController < FrontController
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.js
        RequestMailer.notify_admin(@request).deliver_now
        # RequestMailer.notify_client(@request).deliver_now
      else
        format.js { render partial: 'fail.js' }
        # format.html { render partial: 'fail.js' }
      end
    end
  end

  private

  def request_params
    params.require(:request).permit(Request.attribute_names.map(&:to_sym))
  end
end

app/controllers/front/services_controller.rb
class Front::ServicesController < FrontController
  def index
    @title = "Образы аниматоров на детский праздник | агентство Сказка Шоу"
    @description = "Наши аниматоры могут перевоплотиться в любимые образы героев мультфильмов, сказок и фильмов ваших детей. Образы для малышей, детей от 5 до 7 лет и старше. Вы можете оставить заявку на проведение праздника в Москве с аниматорами на нашем сайте и по телефону: +7 (903) 130-36-64 "
    @keywords = %w(образ детский аниматор заявка)
  end

  def show
  end
end

app/controllers/front/static_pages_controller.rb
class Front::StaticPagesController < FrontController
  def home
    @title = "Организация детских праздников и шоу с аниматорами в Москве | агентство Сказка Шоу"
    @description = "Организация и проведение детских праздников с полным погружением в сказочную атмосферу в Москве. Авторские шоу с профессиональными аниматорами. Поможем организовать детский праздник ребенку, отметить день рождения. Вы можете заказать незабываемый праздник для детей в агентстве детских праздников Сказка шоу: +7 (903) 130-36-64 (WhatsApp)"
    @keywords = %w(детский праздник организация шоу аниматор агентство сказкашоу) << "день рождения"
  end

  def contact
    @title = "Контактная информация агентства детских праздников Сказка Шоу"
    @description = "Контактная информация и режим работы агентства детских праздников Сказка Шоу. Оставить заявку на организацию праздника можно через форму обратной связи на сайте. Адрес офиса: Москва, Пресненская наб., 12, телефон: +7 (903) 130-36-64, info@skazka-show.ru"
    @keywords = %w(контакты информация телефон адрес офис) << "режим работы"
  end

  def new_year
    @title = "Заказать Деда мороза и Снегурочку на дом | Новый Год со Сказка Шоу"
    @description = "Поздравление от Деда Мороза и Снегурочки для детей в Москве; Новый год 2020 с профессиональными аниматорами. Вы можете заказать Деда Мороза и Снегурочку на дом. Новогодний праздник для детей от агентства Сказка Шоу, телефон: +7 (903) 130-36-64"
    @keywords = "дед мороз, снегурочка, заказать, на дом, новый год, детский сад, праздник, стоимость, цена"
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout 'front'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front/requests_helper.rb
module Front::RequestsHelper
end

app/helpers/front/static_pages_helper.rb
module Front::StaticPagesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/front/navigation/_footer.html.haml
/ footer starts
%footer
  / footer-widgets-wrapper starts
  .footer-widgets-wrapper
    / container starts
    .container
      .column.dt-sc-one-fourth.first
        %aside.widget.widget_text
          %h3.widgettitle.red_sketch Сказка Шоу
          %p
            «Сказка Шоу – агентство детских праздников и торжеств. Полное погружение в праздничную атмосферу. Наши преимущества:
          %ul
            %li
              %a{:href => ""} высокий уровень организации,
            %li
              %a{:href => ""} лучшие аниматоры,
            %li
              %a{:href => ""} широкий выбор шоу
            %li
              %a{:href => ""} индивидуальный подбор программы
            %li
              %a{:href => ""} простой способ заказа
      .column.dt-sc-one-fourth
        %aside.widget.widget_recent_entries
          %h3.widgettitle.green_sketch Услуги
          %ul
            %li
              %a{:href => ""}
                %img{:alt => "", :src => asset_path('static/wedding.jpg'), :title => ""}/
                %h6
                  %a{:href => ""} Свадьбы
                / %span Просмотреть все
              %li
                %a{:href => ""}
                  %img{:alt => "", :src => asset_path('static/pen_and_paper.jpg'), :title => ""}/
                  %h6
                    %a{:href => ""} Праздник в ТРЦ
                  / %span March 23, 2014
                %li
                  %a{:href => ""}
                    %img{:alt => "", :src => asset_path('static/cake.jpg'), :title => ""}/
                    %h6
                      %a{:href => ""} Юбилей
                    / %span March 23, 2014
                %li
                  %a{href: ''}
                    %img{:alt => "", :src => asset_path('static/kids.jpg'), :title => ""}/
                    %h6
                      %a{:href => ""} День рождения
                    / %span March 23, 2014
      .column.dt-sc-one-fourth
        %aside.widget.widget_recent_entries
          %h3.widgettitle.yellow_sketch
            %a{:href => ""} Портфолио
          %ul
            %li
              %a{:href => "#portfolio"}
                %img{:alt => "", :src => asset_path('events/001.jpg'), :title => ""}/
                %h6
                  %a{:href => "#portfolio"} Праздник в детском саду
            %li
              %a{:href => "#portfolio"}
                %img{:alt => "", :src => asset_path('events/halloween/1.jpg'), :title => ""}/
                %h6
                  %a{:href => "#portfolio"} Хеллоуин
      .column.dt-sc-one-fourth
        %aside.widget.widget_text
          %h3.widgettitle.steelblue_sketch Контакты
          .textwidget
            %p.dt-sc-contact-info
              %span.fa.fa-map-marker
              Москва, Пресненская наб., 12
              %p.dt-sc-contact-info
                %span.fa.fa-phone
                %a{href: 'tel:+79031303664'}+7 (903) 130-36-64
              %p.dt-sc-contact-info
                %span.fa.fa-envelope
                %a{:href => "mailto:info@skazka-show.ru"} info@skazka-show.ru
          / %aside.widget.mailchimp
          /   %p We're social
          /   %form.mailchimp-form{:action => "php/subscribe.php", :method => "post", :name => "frmnewsletter"}
          /     %p
          /       %span.fa.fa-envelope-o
          /       %input{:name => "mc_email", :placeholder => "Email Address", :type => "email"}/
          /     %input.button{:name => "btnsubscribe", :type => "submit", :value => "Subscribe"}
          /     #ajax_subscribe_msg
        / container ends

  .copyright
    .container
      %p.copyright-info
        © 2019 Skazka Show. Все права защищены. Создание сайта
        %a{:href => "https://blog.handsomecake.com", :title => "HandsomeCake Studios"} Handsomecake Studios
      .footer-links
        %p Мы в соцсетях
        %ul.dt-sc-social-icons
          %li.instagram
            %a{:href => 'https://instagram.com/skazkashow.msk', target: '_blank'}
              %i.fa.fa-instagram
          %li.youtube
            %a{:href => "#"}
              %i.fa.fa-youtube
          / %li.pinterest
          /   %a{:href => "#"}
          /     %img{:alt => "", :src => asset_path("defaults/pinterest.png"), :title => ""}/
/ footer ends

app/views/front/navigation/_header.html.haml
/ header starts
%header
  .container
    .logo
      / %img{:alt => "Kids Life", :src => asset_path("static/clown.jpg"), :title => "Kids Life", class: 'logo-clown'}
      .logo-additional
        =link_to root_path, method: :get do
          %img{:alt => "Kids Life", :src => asset_path("defaults/logo.svg"), :title => "Организация детских праздников 'Сказка шоу'", width: 360}/
    .contact-details
      %p.mail
        %a{:href => "mailto:info@skazka-show.ru"} info@skazka-show.ru
        %span.fa.fa-envelope
      %p.phone-no
        %i
          %a{href: "tel:+79031303664"}+7 (903) 130-36-64
        %span.fa.fa-phone
  / menu-container starts
  #menu-container
    .container
      / nav starts
      %nav#main-menu
        #dt-menu-toggle.dt-menu-toggle
          Menu
          %span.dt-menu-toggle-icon
        %ul#menu-main-menu.menu
          %li.current_page_item.menu-item-simple-parent.menu-item-depth-0.red
            =link_to 'Главная', root_path, method: :get
          %li.mustard
            =link_to 'О нас', root_path(anchor: 'about_us'), method: :get
          %li.menu-item-megamenu-parent.megamenu-4-columns-group.menu-item-depth-0.blue
            %a{:href => "javascript:void(0)", :title => ""} Услуги
            .megamenu-child-container
              %ul.sub-menu
                %li
                  %a{:href => "#"} Шоу
                  %ul.sub-menu
                    %li
                      =link_to 'Лазерное шоу', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Тесла шоу ', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Поролоновое шоу', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Криошоу с мороженным', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Мимы шоу', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Кукольный спектакль', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Ростовые куклы', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Иллюзионная программа', root_path(anchor: 'our_shows'), method: :get
                    %li
                      =link_to 'Барабанное шоу', root_path(anchor: 'our_shows'), method: :get
                  %a.dt-menu-expand +
                %li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-depth-1.menu-item-with-widget-area
                  %a{:href => "#"} Популярное
                  .menu-item-widget-area-container
                    %ul
                      %li.widget.widget_popular_products
                        %ul.product_list_widget
                          %li
                            =link_to contact_path, method: :get do
                              %img{:alt => "Свадьбы", :src => asset_path('static/wedding.jpg'), width: 70, height: 70}/
                              Свадьбы
                            / %span.amount $20.00
                          %li
                            =link_to contact_path, method: :get do
                              %img{:alt => "Праздник в ТРЦ", :src => asset_path('static/pen_and_paper.jpg'), width: 70, height: 70}/
                              Праздник в ТРЦ
                            / %span.amount $20.00
                          %li
                            =link_to contact_path, method: :get do
                              %img{:alt => "Юбилей", :src => asset_path('static/cake.jpg'), width: 70, height: 70}/
                              Юбилей
                            / %span.amount $20.00
                          %li
                            =link_to contact_path, method: :get do
                              %img{:alt => "День рождения", :src => asset_path('static/kids.jpg'), width: 70, height: 70}/
                              День рождения
                %li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-depth-1.menu-item-with-widget-area.fill-two-columns
                  %a{:href => "#"} Образы для детей
                  .menu-item-widget-area-container
                    %ul
                      %li.widget.widget_recent_entries
                        .entry-thumb
                          =link_to services_path, method: :get do
                            %img{:alt => "", :src => asset_path('static/blog_img2.jpg'), :title => ""}/
                        .entry-body
                          %p Образы для малышей. Возраст от 0 до 5 лет.
                        .entry-details
                          .entry-title
                            %h5
                              =link_to 'Оставить заявку', contact_path, method: :get
                          .entry-metadata
                            %p.author
                              =link_to 'Более подробно', services_path, method: :get
                            / %span |
                            / %p.comments
                            /   %a{:href => "#"}
                            /     %span.fa.fa-comment
                            / %p.date 10 Aug
                      %li.widget.widget_recent_entries
                        .entry-thumb
                          =link_to services_path, method: :get do
                            %img{:alt => "", :src => asset_path('static/blog_img1.jpg'), :title => ""}/
                        .entry-body
                          %p Образы для деток. Возрасть от 5 до 7 лет.
                        .entry-details
                          .entry-title
                            %h5
                              =link_to 'Оставить заявку', contact_path, method: :get
                          .entry-metadata
                            %p.author
                              =link_to 'Более подробно', services_path, method: :get
                            / %span |
                            / %p.comments
                            /   %a{:href => "#"}
                            /     %span.fa.fa-comment
                            / %p.date 10 Aug
            %a.dt-menu-expand +

          %li.steelblue
            =link_to 'Тимбилдинги', root_path(anchor: 'teambuilding'), method: :get
          %li.lavender
            =link_to 'Мастер-классы', root_path(anchor: 'masterclass'), method: :get
          %li.yellow
            =link_to 'Образы', services_path, method: :get
          %li.green
            =link_to 'Контакты', contact_path, method: :get
          %li.blue
            =link_to 'Новый Год!', new_year_path, method: :get
      / nav ends
      %ul.dt-sc-social-icons
        %li
          %a.dt-sc-tooltip-top.icon-tik-tok{ href: "#", title: 'Tik Tok', target: '_blank' }
            %span.icon-tik-tok
        %li
          %a.dt-sc-tooltip-top.youtube{ href: "#", title: "Youtube", target: '_blank'}
            %span.fa.fa-youtube
        %li
          %a.dt-sc-tooltip-top.instagram{ href: "https://instagram.com/skazkashow.msk", title: "Instagram", target: '_blank'}
            %span.fa.fa-instagram
        / %li
        /   %a.dt-sc-tooltip-top.gplus{:href => "#", :title => "Google Plus"}
        /     %span.fa.fa-google-plus
  / menu-container ends
/ header ends

app/views/front/requests/_fail.js.erb
var cf = $('#contact-form');
cf.append('<div class="dt-sc-titled-box mustard"></div>');

if(cf.find('textarea').val().length < 20){
  text = "Сообщение слишком короткое..."
}
if(cf.find('input').val() == ""){
  text = "Все поля должны быть заполнены";
}
$('.dt-sc-titled-box .mustard').html('<h4 class="dt-sc-titled-box-title">Ошибка </h4><div class="dt-sc-titled-box-content"><p>'+text+'</p></div>')
  .delay(150)
  .slideDown(300)
  .delay(4000)
  .slideUp(300,function(){
    $(this).html("");
  });

app/views/front/requests/create.js.erb
var cf = $('#contact-form');
cf.append('<div class="dt-sc-titled-box"></div>');

text = "Спасибо за Ваше обращение! Мы его получили.";

cf.find('input:not([type="submit"]),textarea').val('');

$('.dt-sc-titled-box').html('<h4 class="dt-sc-titled-box-title">Все удачно :) </h4><div class="dt-sc-titled-box-content"><p>'+text+'</p></div>')
  .delay(150)
  .slideDown(300)
  .delay(4000)
  .slideUp(300,function(){
    $(this).html("");
  });

app/views/front/services/index.haml
/ breadcrumb-section starts
.breadcrumb-section
  .container
    %h1 Услуги
    .breadcrumb
      %a{:href => root_path} Главная
      %span.fa.fa-angle-double-right
      %span.current Услуги
/ breadcrumb-section ends
/ container starts
.container
  / primary starts
  %section#primary.content-full-width
    .dt-sc-one-column
      %article.blog-entry
        .blog-entry-inner
          .entry-meta
            %a.blog-author{:href => ''}
              %img{:alt => "", :src => asset_path('static/rounded-bg-img.jpg'), :title => ""}/
            .date
              %span М
              %p
                Возраст
                %br/
                0-5
          .entry-thumb
            %img{:alt => "", :src => asset_path('static/blog_img2.jpg'), :title => ""}/
          .entry-details
            .entry-title
              %h3
                %a{:href => ''} Образы для малышей:
            / entry-metadata ends
            .entry-body
              %ul.dt-sc-fancy-list.pink.star
                %li Из мультфильма «Три кота» - Карамелька, Коржик, Компот.
                %li Из мультфильма « Фиксики» - Симка, Нолик, Фаер
                %li Из мультфильма «Свинка Пеппа»- Свинка Пеппа, Джордж
                %li Зайчики, мишки.
                %li Лунтик, Мила
                %li Смешарики: Крош, Нюша
            %a.dt-sc-button.small{:href => contact_path}
              Оставить заявку
              %span.fa.fa-chevron-circle-right
    .dt-sc-one-column
      %article.blog-entry
        .blog-entry-inner
          .entry-meta
            %a.blog-author{:href => "blog-detail.html"}
              %img{:alt => "", :src => asset_path('static/rounded-bg-img.jpg'), :title => ""}/
            .date
              %span Д
              %p
                Возраст
                %br/
                5-7
          .entry-thumb
            %a{:href => ''}
              %img{:alt => "", :src => asset_path('static/blog_img1.jpg'), :title => ""}/
          .entry-details
            .entry-title
              %h3
                %a{:href => ''} Образы для деток 5-7 лет:
            / entry-metadata ends
            .entry-body
              %ul.dt-sc-fancy-list.burnt-orange.star
                %li Леди Баг и Супер кот.
                %li «Щенячий патруль»- Скай, Дружок, Маршал
                %li Рапунцель
                %li Мерида
                %li «Холодное сердце»- Эльза, Анна, Олаф
                %li Русалочка
                %li Бель
                %li Белоснежка
                %li Жасмин и Алладин
                %li Золушка
                %li Ариэль
                %li Аврора
                %li Принцесса София
                %li Моана и Мауи
                %li Куклы Лол: Единорожка Лол, Балерина Лол, Пчелка Лол
                %li Пони Искорка, Пони Селестия, Пони Рарити, Пони Эплджек, Пони Радуга,
                %li Динь-Динь
                %li Снежная Королева
                %li «Феи Винкс»- Блум, Стелла, Муза, Флора
                %li «Сказочный патруль» - Варя, Снежка, Аленка
                %li Клоунесса и Клоун
                %li Пираты
                %li Миньоны
                %li «Барбароскины»- Роза, Дружок, Лиза
                %li Алиса
                %li Вспыш
                %li «Тачки»- Маквин, Салли
                %li Капитан Америка
                %li Человек Паук
                %li Халк
                %li Железный человек
                %li Супермен и супервумен
                %li Бэтмен
                %li Бамбалби трансформер
                %li Оптимус Прайм
                %li Из « Тролли» Цветан и Розочка
                %li Микки и Мини Маус
                %li Черепашки Ниндзя
                %li Машенька и медведь
                %li «Мимимишки»- Кеша, Тучка, Цыпа
                %li Эмбер, Полли Робокар
                %li Майнкрафт Крипер
                %li Энгри Бердс: Ред,
                %li Лего нинзяго, Лего нинзяго Кай, Лего нинзяго Синий, красный
                %li «Герои в масках» - Аллет, Кэтбой
                %li Флэш
            %a.dt-sc-button.small{:href => contact_path}
              Оставить заявку
              %span.fa.fa-chevron-circle-right
    .dt-sc-one-column
      %article.blog-entry
        .blog-entry-inner
          .entry-meta
            %a.blog-author{:href => "blog-detail.html"}
              %img{:alt => "", :src => asset_path('static/rounded-bg-img.jpg'), :title => ""}/
            .date
              %span Д
              %p
                Возраст
                %br/
                7 и старше
          .entry-thumb
            %a{:href => ''}
              %img{:alt => "", :src => asset_path('static/blog_img3.jpg'), :title => ""}/
          .entry-details
            .entry-title
              %h3
                %a{:href => ''} Для детей старше 7 лет:
            / entry-metadata ends
            .entry-body
              %ul.dt-sc-fancy-list.violet.star
                %li Модные ведущие
                %li Гарри Потёр и Гермиона
                %li Дракула, ведьма
                %li Ковбои
                %li «Звездные войны» -Дарт Вейдер и  Лея, Джедай
                %li Индейцы
                %li You mube
                %li Джек Воробей
                %li Дэдпул
                %li Шляпник
                %li Алиса
                %li Бременские музыканты
                %li Спанч Боб
                %li Археологи
                %li Шиммер Шайн
                %li «Граффити Фолз»- Мейбл Диппер
                %li Фьеки
                %li Харли Квин
            %a.dt-sc-button.small{:href => contact_path}
              Оставить заявку
              %span.fa.fa-chevron-circle-right
  / primary ends
/ container ends

app/views/front/shared/_contact_form.haml
=form_with model: Request.new, class: 'contact-form', id: 'contact-form' do |f|
  -if title
    %h2=title
  -else
    %h2="Заказать звонок"
  %p.column.dt-sc-one-half.first
    =f.text_field :name, placeholder: 'Ваше имя', id: 'name', required: true
  %p.column.dt-sc-one-half
    =f.text_field :phone, placeholder: 'Телефон', id: 'phone', required: true
  %p
    =f.text_area :body, placeholder: 'Ваша идея праздника', id: 'comment', required: true
  #ajax_contact_msg
  %p
    =f.submit 'Отправить', class: 'dt-sc-button medium', id: 'submit', data: { "disable_with" => "Отправляем..."}

app/views/front/static_pages/contact.haml
/ breadcrumb-section starts
.breadcrumb-section
  .container
    %h1 Контакты
    .breadcrumb
      %a{:href => root_path} Главная
      %span.fa.fa-angle-double-right
      %span.current Контакты
/ breadcrumb-section ends
/ container starts
.container
  / primary starts
  %section#primary.content-full-width
    #yandex_map{style: "width: 100%; height: 400px"}
    .dt-sc-hr
    / dt-sc-two-third starts
    .column.dt-sc-three-fourth.first.contact_form_outer
      =render partial: 'front/shared/contact_form', locals: { title: "Оставить заявку на организацию праздника" }
    / dt-sc-two-third ends
    / dt-sc-one-third starts
    .column.dt-sc-one-fourth.class_hours
      %h2 Часы работы
      %ul.class_hours
        %li
          Понедельник
          %span 9am - 3pm
        %li
          Вторник
          %span 9am - 3pm
        %li
          Среда
          %span 9am - 3pm
        %li
          Четверг
          %span 9am - 3pm
        %li
          Пятница
          %span 9am - 3pm
        %li
          Суббота
          %span Holiday
        %li
          Воскресенье
          %span Holiday
      .dt-sc-hr-small
    .dt-sc-hr

    / dt-sc-one-third ends
  / primary ends
/ container ends

app/views/front/static_pages/home.html.haml
#main
  / slider starts
  / #slider_placeholder
  =render partial: 'front/static_pages/home_partials/slider'
  / slider ends
  / primary starts
  %section#primary.content-full-width
    #about_us
      =render partial: 'front/static_pages/home_partials/about_us'
    .dt-sc-hr
    / fullwidth_banner starts
    %section
      .container
        %h1{style: "text-align: center; color: #F1F3F3;"} Услуги
      / fullwidth_banner ends
      / primary starts
    %section.fullwidth_banner.max-height
      =render partial: 'front/static_pages/home_partials/services'
      / fullwidth-background starts
      / %section.fullwidth-background.dt-sc-parallax-section.turquoise-bg
      / =render partial: 'front/static_pages/home_partials/services_description'
      / fullwidth-background ends
    %section
      .dt-sc-hr
      =render partial: 'front/static_pages/home_partials/portfolio'
      .dt-sc-hr

    %section.fullwidth-background.dt-sc-parallax-section.product_bg{:style => "background-position: 50% 54px;"}
      #elza_show
        =render partial: 'front/static_pages/home_partials/show_elza'

    %section
      .dt-sc-hr
      =render partial: 'front/static_pages/home_partials/teambuilding'

    %section.fullwidth-background.dt-sc-parallax-section.turquoise-bg{:style => "background-position: 50% -59px;"}
      =render partial: 'front/static_pages/home_partials/masterclass'
    %section.fullwidth-background.dt-sc-parallax-section.orange-bg
      #contact
        / container starts
        / =render partial: "front/static_pages/home_partials/blog"
        =render partial: "front/static_pages/home_partials/contact"

      / primary ends
      / main ends

app/views/front/static_pages/home_partials/_about_us.haml
.container
  %h2.dt-sc-hr-green-title Организация сказочных детских праздников и шоу с профессиональными аниматорами в Москве
  %p.text-justify.padding-bottom-10
    Агентство "Сказка Шоу" занимается организацией и проведением детских праздников. Наши аниматоры проводят праздники для детей с полным погружением в сказочную атмосферу. Мы делаем авторские шоу-программы. У нас в агентстве можно недорого заказать праздник в детском саду, в беби-клубе, торговом центре и иных детских заведениях. Мы поможем качественно организовать детский праздник ребенку, отметить день рождения с индивидуальной шоу-программой, конкурсами для детей и фокусами. Самое важное для родителей - детская улыбка и радость. Для них мы разрабатываем сценарии мероприятий, готовим костюмы, репетируем выступления и конкурсы. Наши профессиональные аниматоры подарят счастье вашим деткам!

/ container starts
.container
  .dt-sc-one-fourth.column.first
    .dt-sc-ico-content.type1
      .icon
        %span.icon-outer
          %img{:alt => "", :src => asset_path('static/wedding.jpg'), :title => ""}/
          %span.infolayer
            %a{:href => "#"}
              %i.fa.fa-link
      %h4
        %a{:href => ""} Свадьбы
  .dt-sc-one-fourth.column
    .dt-sc-ico-content.type1
      .icon
        %span.icon-outer
          %img{:alt => "", :src => asset_path('static/pen_and_paper.jpg'), :title => ""}/
          %span.infolayer
            %a{:href => "#"}
              %i.fa.fa-link
      %h4
        %a{:href => ""} Праздник в ТРЦ
  .dt-sc-one-fourth.column
    .dt-sc-ico-content.type1
      .icon
        %span.icon-outer
          %img{:alt => "", :src => asset_path('static/cake.jpg'), :title => ""}/
          %span.infolayer
            %a{:href => "#"}
              %i.fa.fa-link
      %h4
        %a{:href => ""} Юбилей
  .dt-sc-one-fourth.column
    .dt-sc-ico-content.type1
      .icon
        %span.icon-outer
          %img{:alt => "", :src => asset_path('static/kids.jpg'), :title => ""}/
          %span.infolayer
            %a{:href => "#"}
              %i.fa.fa-link
      %h4
        %a{:href => ""} День рождения
/ container ends

app/views/front/static_pages/home_partials/_contact.html.haml
/ container starts
.container
  / primary starts
  %section#primary.content-full-width
    .column.dt-sc-one-column.first.contact_form_outer
      =render partial: 'front/shared/contact_form', locals: { title: "Заказать детский праздник" }

app/views/front/static_pages/home_partials/_slider.html.haml
.glide
  .glide__track{"data-glide-el" => "track"}
    %ul.glide__slides
      %li.glide__slide
        %img{:src => asset_path('slider/winter_holidays/1.jpg'), :style => "width:100%"}/
      %li.glide__slide
        %img{:src => asset_path('slider/winter_holidays/2.jpg'), :style => "width:100%"}/
      %li.glide__slide
        %img{:src => asset_path('slider/winter_holidays/3.jpg'), :style => "width:100%"}/
      %li.glide__slide
        %img{:src => asset_path('slider/main_bg.png'), :style => "width:100%"}/


  .glide__bullets{"data-glide-el" => "controls[nav]"}
    %button.glide__bullet{"data-glide-dir" => "=0"}
    %button.glide__bullet{"data-glide-dir" => "=1"}
    %button.glide__bullet{"data-glide-dir" => "=2"}
    %button.glide__bullet{"data-glide-dir" => "=3"}

app/views/services/index.html.haml
%h1 Services#index
%p Find me in app/views/services/index.html.haml